services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: yunojuno
      POSTGRES_USER: yunojuno
      POSTGRES_PASSWORD: yunojuno
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data:
