# Generated by Django 5.2.14 on 2026-06-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='timesheet_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='line_item', to='contracts.timesheetentry'),
        ),
    ]
